Add controllers
alex1261bat/java-shareit pull request #1
Opened 2022-12-03 17:26 UTC by alex1261bat

2022-12-04 23:13 UTC, alexache requested changes

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private long owner;
В моделях лучше хранить связанные объекты моделей, а не просто id, то есть User owner, ItemRequest request и так далее

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item saveNewItem(@RequestHeader("X-Sharer-User-Id") Long userId,
Нужно разделить классы: ДТО для взаимодействия со входным данными (на вход-выход контроллера, вход=выход сервиса) и модели для хранения (от сервиса к репозиторию/стораджу)

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
Когда этот класс будет полноценной моделью, а не как входные данные, нужно будет убрать эти клиентские валидации

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item add(Long userId, Item item);
В интерфейсе сервисов должны использоваться только ДТО объекты, а не-ДТО (модели) в стораджах

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    ItemDto getById(Long userId, Long itemId) throws NotFoundException;
Сторадж не должен работать с ДТО классами

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemStorage.add(userId, item);
Когда будет разделение на ДТО и модель, сервис должен будет вызывать маппер в обе стороны: как часть своей связующей функции

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        for (Item element : itemList) {
Не очень хороший способ, если у каких-то пользователей будет очень много вещей - будет полный перебор всех элементов списка. Можно разделить мапу на 2 -  одна как текущая, а вторая для маппинга айди вещи на объект вещи (тогда такой запрос будет быстрым)

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemStorage.update(userId, itemId, item);
А где проверка,  что вещь может редактировать только ее владелец?

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        return userItems.stream().map(ItemMapper::toItemDto).collect(Collectors.toList());
Конвертацию должен вызывать сервис

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +            return new ArrayList<>();
В таких случаях лучше использовать Collections.emptyList() чтобы не создавать пустые списки

2022-12-04 23:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +                if ((item.getName().toLowerCase().contains(text.toLowerCase())
text.toLowerCase() можно вынести за пределы цикла

2022-12-05 17:36 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    private long owner;
исправлено

2022-12-05 18:11 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    ItemDto getById(Long userId, Long itemId) throws NotFoundException;
исправлено

2022-12-05 18:14 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +            return new ArrayList<>();
исправлено

2022-12-05 18:22 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +                if ((item.getName().toLowerCase().contains(text.toLowerCase())
исправлено

2022-12-05 18:38 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        return userItems.stream().map(ItemMapper::toItemDto).collect(Collectors.toList());
исправлено

2022-12-05 19:44 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        for (Item element : itemList) {
исправлено

2022-12-05 19:44 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemStorage.update(userId, itemId, item);
исправлено

2022-12-05 19:45 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item saveNewItem(@RequestHeader("X-Sharer-User-Id") Long userId,
исправлено

2022-12-05 19:45 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
возможно исправлено, если я правильно понял

2022-12-05 19:53 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemStorage.add(userId, item);
исправлено

2022-12-06 13:36 UTC, alexache approved these changes

2022-12-06 13:36 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> -    private long owner;
Вот здесь лучше было оставлять как было - просто айди

2022-12-06 13:36 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        setItemId(itemId + 1);
Сеттеры обычно используются извне. Если внутри того же класса, то это обычно излишне

2022-12-06 14:08 UTC, merged