feat: реализовать add-bookings
alex1261bat/java-shareit pull request #2
Opened 2023-01-16 20:13 UTC by alex1261bat

2023-01-18 15:11 UTC, alexache requested changes

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.getAllUserBookings(userId, state);
(опционально) Можно конвертировать в енам уже в контроллере

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingResponseDto.java
> +    private User booker;
Плохо смешивать ДТО и модели. ДТО должны использовать ДТО, а модели - модели

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User booker = UserMapper.toUser(userService.getById(userId));
Может лучше использовать репозиторий? Иначе довольно странно сначала конвертировать в это, а затем следом в обратную сторону

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/CommentStorage.java
> +    @Query("select c from Comment c " +
Разве нужно отдельным query или можно с помощью naming добиться того же?

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        User owner = UserMapper.toUser(userService.getById(userId));
Здесь тоже можно бы репозиторий вместо сервиса

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private ItemWithBookingDatesDto convertItem(Item item, long userId) {
Из названия не очень понятно. что делает метод

2023-01-18 15:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>      private long requestor;
Лучше иметь объект User

2023-01-18 15:48 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>      private long requestor;
Исправлено

2023-01-18 15:50 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private ItemWithBookingDatesDto convertItem(Item item, long userId) {
Исправлено

2023-01-18 16:35 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        User owner = UserMapper.toUser(userService.getById(userId));
Исправлено

2023-01-18 16:46 UTC, anzerdev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User booker = UserMapper.toUser(userService.getById(userId));
Исправлено

2023-01-18 16:47 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/item/CommentStorage.java
> +    @Query("select c from Comment c " +
Исправлено

2023-01-18 16:52 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/booking/BookingResponseDto.java
> +    private User booker;
Исправлено

2023-01-18 16:56 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.getAllUserBookings(userId, state);
Решил оставить как есть

2023-01-19 13:26 UTC, alexache approved these changes

2023-01-19 16:33 UTC, merged