feat: реализовать add-items-requests
alex1261bat/java-shareit pull request #3
Opened 2023-01-21 21:11 UTC by alex1261bat

2023-01-23 18:11 UTC, alexache requested changes

2023-01-23 18:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private PageRequest validatePage(Integer from, Integer size) {
(опционально) метод может быть и статическим

2023-01-23 18:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    itemRepository.findAllByRequestId(request.getId()).stream()
Запросы к базе в цикле - это плохой способ. нужен один запрос по списку requestId, и дальше можно полученные данные использоваться для наполнения ответа

2023-01-23 18:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTest/BookingControllerTest.java
> +    BookingService bookingService;
Не хватает модификатора доступа

2023-01-23 18:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTest/BookingControllerTest.java
> +                .andExpect(jsonPath("$.id", is(bookingDto.getId()), Long.class));
Надо еще валидировать, что метод сервиса был действительно вызван и единожды через  verify(bookingService, times(1)).saveNewBooking(...), и так в других тест кейсах

2023-01-23 18:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTest/BookingRepositoryTest.java
> +    BookingRepository bookingRepository;
Модификаторы доступа у полей

2023-01-23 18:11 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTest/BookingServiceImplTest.java
> +    void getAllUserBookingsTest() {
На самом деле, это больше похоже на 6 тестов в одном. Тесты делятся не по методам, которые они покрывают, а по тесткейсам. Тут 6-7 разных тесткейсов в одном тест методе. Лучше разделить

2023-01-24 12:21 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private PageRequest validatePage(Integer from, Integer size) {
исправлено

2023-01-24 13:37 UTC, alex1261bat commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                    itemRepository.findAllByRequestId(request.getId()).stream()
исправлено

2023-01-24 18:05 UTC, alex1261bat commented on src/test/java/ru/practicum/shareit/bookingTest/BookingControllerTest.java
> +    BookingService bookingService;
исправлено

2023-01-24 18:05 UTC, alex1261bat commented on src/test/java/ru/practicum/shareit/bookingTest/BookingRepositoryTest.java
> +    BookingRepository bookingRepository;
исправлено

2023-01-24 19:08 UTC, alex1261bat commented on src/test/java/ru/practicum/shareit/bookingTest/BookingControllerTest.java
> +                .andExpect(jsonPath("$.id", is(bookingDto.getId()), Long.class));
исправлено

2023-01-24 20:00 UTC, alex1261bat commented on src/test/java/ru/practicum/shareit/bookingTest/BookingServiceImplTest.java
> +    void getAllUserBookingsTest() {
исправлено

2023-02-02 21:54 UTC, alexache approved these changes

2023-02-04 18:01 UTC, merged