feat: реализовать add-docker
alex1261bat/java-shareit pull request #5
Opened 2023-02-09 10:22 UTC by alex1261bat

2023-02-10 14:35 UTC, alexache requested changes

2023-02-10 14:35 UTC, alexache commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +        return bookingClient.saveNewBooking(userId, requestDto);
Не помешает логгирований операций

2023-02-10 14:35 UTC, alexache commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +        return bookingClient.saveNewBooking(userId, requestDto);
Сюда стоит перенести проверку из сервиса бронирований - if (bookingRequestDto.getStart().isAfter(bookingRequestDto.getEnd())) {
            throw new ValidationException("Время начала бронирования не может быть позже времени окончания");
        }
        Это относится к валидациям

2023-02-10 14:35 UTC, alexache commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +                                                     @RequestParam(name = "from",
Валидации from/size полей лучше добавить в контроллере здесь, чем в клиенте

2023-02-10 14:35 UTC, alexache commented on gateway/src/main/java/ru/practicum/gateway/request/ItemRequestClient.java
> +        PageValidator.validatePage(from, size);
Мне кажется, это более правильно и наглядно делать в контроллере (гейтвея), а не клиенте

2023-02-10 14:35 UTC, alexache commented on server/pom.xml
> +            <artifactId>jakarta.validation-api</artifactId>
Не должно оставаться валидаций в компоненте сервера

2023-02-10 14:35 UTC, alexache commented on server/pom.xml
> +            <groupId>ru.practicum</groupId>
Для чего зависимость сервера от гейтвея?

2023-02-10 15:40 UTC, alex1261bat commented on server/pom.xml
> +            <groupId>ru.practicum</groupId>
исправлено

2023-02-10 15:41 UTC, alex1261bat commented on server/pom.xml
> +            <artifactId>jakarta.validation-api</artifactId>
исправлено

2023-02-10 17:08 UTC, alex1261bat commented on gateway/src/main/java/ru/practicum/gateway/request/ItemRequestClient.java
> +        PageValidator.validatePage(from, size);
исправлено

2023-02-10 17:08 UTC, alex1261bat commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +                                                     @RequestParam(name = "from",
исправлено

2023-02-10 17:12 UTC, alex1261bat commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +        return bookingClient.saveNewBooking(userId, requestDto);
исправлено

2023-02-10 18:25 UTC, alex1261bat commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +        return bookingClient.saveNewBooking(userId, requestDto);
исправлено

2023-02-11 20:27 UTC, alexache approved these changes

2023-02-12 17:05 UTC, merged